-- AlterTable
ALTER TABLE "PRODUTO" ADD COLUMN     "CODUSU" INTEGER;

-- AddForeignKey
ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "LOGIN"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;
