-- CreateTable
CREATE TABLE "LOGIN" (
    "CODUSU" SERIAL NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "PERMISSAO" TEXT DEFAULT 'CLIENTE',

    CONSTRAINT "LOGIN_pkey" PRIMARY KEY ("CODUSU")
);

-- CreateTable
CREATE TABLE "INFOS" (
    "CODPES" SERIAL NOT NULL,
    "NOME" TEXT NOT NULL,
    "SOBRENOME" TEXT NOT NULL,
    "CPF" TEXT NOT NULL,
    "TELEFONE" TEXT NOT NULL,
    "CODUSU" INTEGER NOT NULL,

    CONSTRAINT "INFOS_pkey" PRIMARY KEY ("CODPES")
);

-- CreateTable
CREATE TABLE "ENDERECOS" (
    "CODEND" SERIAL NOT NULL,
    "CEP" TEXT NOT NULL,
    "RUA" TEXT NOT NULL,
    "NUMERO" TEXT NOT NULL,
    "BAIRRO" TEXT NOT NULL,
    "CIDADE" TEXT NOT NULL,
    "COMPLEMENTO" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "CODPES" INTEGER NOT NULL,

    CONSTRAINT "ENDERECOS_pkey" PRIMARY KEY ("CODEND")
);

-- CreateTable
CREATE TABLE "Categorias" (
    "CODCAT" SERIAL NOT NULL,
    "CATEGORIA" TEXT NOT NULL,

    CONSTRAINT "Categorias_pkey" PRIMARY KEY ("CODCAT")
);

-- CreateTable
CREATE TABLE "PRODUTO" (
    "CODPROD" SERIAL NOT NULL,
    "PRODUTO" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "IMAGEM" TEXT NOT NULL,
    "ESTOQUE" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "VALOR" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "DESCONTO" DOUBLE PRECISION DEFAULT 0,
    "CODCAT" INTEGER,

    CONSTRAINT "PRODUTO_pkey" PRIMARY KEY ("CODPROD")
);

-- CreateTable
CREATE TABLE "AVALIACOES" (
    "CODAVA" SERIAL NOT NULL,
    "NOTA" INTEGER NOT NULL,
    "COMENTARIO" TEXT,
    "CODPROD" INTEGER NOT NULL,
    "CODPES" INTEGER NOT NULL,
    "DATAINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AVALIACOES_pkey" PRIMARY KEY ("CODAVA")
);

-- CreateTable
CREATE TABLE "PEDIDOS" (
    "CODPED" SERIAL NOT NULL,
    "SUBTOTAL" DOUBLE PRECISION DEFAULT 0,
    "VALORTOTAL" DOUBLE PRECISION DEFAULT 0,
    "DESCONTO" DOUBLE PRECISION DEFAULT 0,
    "FRETE" DOUBLE PRECISION DEFAULT 0,
    "CODEND" INTEGER,
    "CODPES" INTEGER,
    "DATAINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PEDIDOS_pkey" PRIMARY KEY ("CODPED")
);

-- CreateTable
CREATE TABLE "ItensPedido" (
    "CODITEM" SERIAL NOT NULL,
    "TAMANHO" TEXT,
    "QTD" INTEGER,
    "CODPROD" INTEGER,
    "CODPED" INTEGER,

    CONSTRAINT "ItensPedido_pkey" PRIMARY KEY ("CODITEM")
);

-- CreateIndex
CREATE UNIQUE INDEX "LOGIN_EMAIL_key" ON "LOGIN"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "INFOS_CODUSU_key" ON "INFOS"("CODUSU");

-- CreateIndex
CREATE UNIQUE INDEX "PRODUTO_PRODUTO_key" ON "PRODUTO"("PRODUTO");

-- CreateIndex
CREATE UNIQUE INDEX "AVALIACOES_CODPROD_CODPES_key" ON "AVALIACOES"("CODPROD", "CODPES");

-- AddForeignKey
ALTER TABLE "INFOS" ADD CONSTRAINT "INFOS_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "LOGIN"("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ENDERECOS" ADD CONSTRAINT "ENDERECOS_CODPES_fkey" FOREIGN KEY ("CODPES") REFERENCES "INFOS"("CODPES") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_CODCAT_fkey" FOREIGN KEY ("CODCAT") REFERENCES "Categorias"("CODCAT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AVALIACOES" ADD CONSTRAINT "AVALIACOES_CODPROD_fkey" FOREIGN KEY ("CODPROD") REFERENCES "PRODUTO"("CODPROD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AVALIACOES" ADD CONSTRAINT "AVALIACOES_CODPES_fkey" FOREIGN KEY ("CODPES") REFERENCES "INFOS"("CODPES") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_CODEND_fkey" FOREIGN KEY ("CODEND") REFERENCES "ENDERECOS"("CODEND") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_CODPES_fkey" FOREIGN KEY ("CODPES") REFERENCES "INFOS"("CODPES") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ItensPedido" ADD CONSTRAINT "ItensPedido_CODPROD_fkey" FOREIGN KEY ("CODPROD") REFERENCES "PRODUTO"("CODPROD") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ItensPedido" ADD CONSTRAINT "ItensPedido_CODPED_fkey" FOREIGN KEY ("CODPED") REFERENCES "PEDIDOS"("CODPED") ON DELETE SET NULL ON UPDATE CASCADE;
